"use client";
import { useState } from "react";
import { BarChart3, Download, LockKeyhole, RefreshCw, ShieldAlert } from "lucide-react";

type Analytics = { generatedAt: string; leads: { total: number; byType: Record<string,number>; bySize: Record<string,number>; byInterest: Record<string,number>; byDay: Record<string,number>; tools: Record<string,number> }; threat: { total:number; ransomware:number; added30d:number; vendors:Record<string,number>; updated:string|null; source:string } };

function Bars({ data }: { data: Record<string,number> }) { const max = Math.max(1,...Object.values(data)); return <div className="data-bars">{Object.entries(data).map(([label,value])=><div key={label}><span>{label}</span><i><b style={{width:`${value/max*100}%`}}/></i><strong>{value}</strong></div>)}</div> }

export function AdminDashboard() {
  const [token,setToken]=useState(""); const [data,setData]=useState<Analytics|null>(null); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  async function load(){setLoading(true);setError("");try{const r=await fetch("/api/analytics",{cache:"no-store",headers:{"x-admin-token":token}});const j=await r.json() as Analytics & {error?:string};if(!r.ok)throw new Error(j.error||"Unable to load dashboard");setData(j)}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard")}finally{setLoading(false)}}
  async function download(){setError("");try{const r=await fetch("/api/export",{headers:{"x-admin-token":token}});if(!r.ok)throw new Error("Unable to export the lead register");const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`Aronxx_Tech_Lead_Register_${new Date().toISOString().slice(0,10)}.xlsx`;a.click();URL.revokeObjectURL(url)}catch(e){setError(e instanceof Error?e.message:"Unable to export the lead register")}}
  if(!data)return <div className="admin-login"><LockKeyhole/><h1>Private analytics</h1><p>Enter the administrator token configured in your hosting environment.</p><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Administrator token"/><button className="btn" onClick={load} disabled={!token||loading}>{loading?"Loading…":"Open dashboard"}</button>{error&&<p className="form-error">{error}</p>}</div>;
  return <main className="admin-shell"><header><div><span className="eyebrow"><BarChart3/> Live intelligence</span><h1>Aronxx Tech request analytics</h1><p>Last refreshed {new Date(data.generatedAt).toLocaleString()}</p></div><div className="admin-actions"><button className="btn btn-ghost" onClick={load}><RefreshCw/> Refresh</button><button className="btn" onClick={download}><Download/> Export Excel</button></div></header>{error&&<p className="form-error">{error}</p>}<section className="admin-metrics"><article><span>Total requests</span><b>{data.leads.total}</b></article><article><span>Known exploited vulnerabilities</span><b>{data.threat.total||"—"}</b></article><article><span>CISA additions · 30 days</span><b>{data.threat.added30d||"—"}</b></article><article><span>Known ransomware use</span><b>{data.threat.ransomware||"—"}</b></article></section><section className="admin-grid"><article><h2>Requests by type</h2><Bars data={data.leads.byType}/></article><article><h2>Company size</h2><Bars data={data.leads.bySize}/></article><article><h2>Pilot interest</h2><Bars data={data.leads.byInterest}/></article><article><h2>AI tools mentioned</h2><Bars data={data.leads.tools}/></article><article className="wide-panel"><h2>Request activity by day</h2><Bars data={data.leads.byDay}/></article><article className="wide-panel"><h2><ShieldAlert/> Live threat context by vendor</h2><Bars data={data.threat.vendors}/><p className="source-note">Live public feed: {data.threat.source}. Updated hourly when available. This is general exploitation context, not a claim about Aronxx Tech detections.</p></article></section></main>;
}
