"use client";
import { useEffect, useMemo, useState } from "react";
import { Activity, Building2, CircleDollarSign, Clock3, DatabaseZap, RefreshCw, ShieldAlert } from "lucide-react";

type Sector = { id:string; name:string; branches:string[]; need:number; aiExposure:number; risk:number; lossMin:number; lossMax:number; lossDrivers:string[]; sensitiveData:string[] };
type Intelligence = { generatedAt:string; live:boolean; feedReleasedAt:string|null; threat:{knownExploited:number;added30d:number;ransomware:number;trend:{month:string;count:number}[]}; sectors:Sector[]; methodology:string; sources:{name:string;url:string;cadence:string}[] };

function money(value:number){return value < 1 ? `$${Math.round(value*1000)}K` : `$${value.toFixed(1)}M`}

export function IndustryIntelligence(){
  const [data,setData]=useState<Intelligence|null>(null); const [selected,setSelected]=useState("all"); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  async function load(){setLoading(true);setError("");try{const response=await fetch("/api/industry-intelligence",{cache:"no-store"});if(!response.ok)throw new Error("Live intelligence is temporarily unavailable");setData(await response.json() as Intelligence)}catch(e){setError(e instanceof Error?e.message:"Unable to load intelligence")}finally{setLoading(false)}}
  useEffect(()=>{const initial=window.setTimeout(()=>void load(),0);const timer=window.setInterval(()=>void load(),3600000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[]);
  const sectors=useMemo(()=>data?.sectors.filter(x=>selected==="all"||x.id===selected)||[],[data,selected]);
  const selectedSector=useMemo(()=>data?.sectors.find(x=>x.id===selected),[data,selected]);
  const subSectors=useMemo(()=>{if(!data||!selectedSector)return[];const livePressure=Math.min(8,Math.round(data.threat.added30d/5+data.threat.ransomware/100));return selectedSector.branches.slice(0,2).map((name,index)=>({name,need:Math.min(100,Math.max(1,selectedSector.need-index*4+livePressure)),exposure:Math.min(100,Math.max(1,selectedSector.aiExposure-index*6+Math.round(livePressure/2)))}))},[data,selectedSector]);
  const maxTrend=Math.max(1,...(data?.threat.trend.map(x=>x.count)||[1]));
  if(loading&&!data)return <section className="industry-live"><div className="intel-loading"><Activity/> Loading live industry intelligence…</div></section>;
  if(error&&!data)return <section className="industry-live"><div className="intel-error"><ShieldAlert/>{error}<button onClick={load}>Retry</button></div></section>;
  return <section className="industry-live">
    <div className="intel-heading"><div><span className="eyebrow"><Activity/> Live industry intelligence</span><h2>Where AI data exposure creates the greatest business risk.</h2><p>Explore sectors and sub-sectors that may benefit from Aronxx Tech. Reported public signals and modeled exposure estimates are kept clearly separate.</p></div><div className={`live-badge ${data?.live?"is-live":"benchmark"}`}><i/>{data?.live?"PUBLIC FEED LIVE":"BENCHMARK MODE"}</div></div>
    <div className="intel-controls"><label>Industry<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="all">All industries</option>{data?.sectors.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><button onClick={load} disabled={loading}><RefreshCw className={loading?"spinning":""}/> Refresh intelligence</button><span><Clock3/> Updated {data&&new Date(data.generatedAt).toLocaleString()}</span></div>
    <div className="intel-metrics"><article><DatabaseZap/><span>Known exploited vulnerabilities</span><b>{data?.threat.knownExploited||"—"}</b><small>Reported · CISA KEV</small></article><article><Activity/><span>Added in last 30 days</span><b>{data?.threat.added30d||"—"}</b><small>Live pressure signal</small></article><article><ShieldAlert/><span>Known ransomware use</span><b>{data?.threat.ransomware||"—"}</b><small>Reported · CISA KEV</small></article><article><Building2/><span>Industries modeled</span><b>{data?.sectors.length||12}</b><small>{data?.sectors.reduce((n,x)=>n+x.branches.length,0)||48} sub-sectors</small></article></div>
    <div className="intel-layout"><article className="risk-ranking"><header><div><span>Comparative model</span><h3>Industry need and exposure</h3></div><span className="model-chip">0–100 index</span></header><div className="sector-bars">{sectors.map(sector=><button key={sector.id} onClick={()=>setSelected(sector.id)}><span>{sector.name}</span><i><b style={{width:`${sector.need}%`}}/></i><strong>{sector.need}</strong></button>)}</div>{selected!=="all"&&subSectors.length>0&&<div className="subsector-breakdown"><div className="subsector-title"><div><span>Selected sub-sector view</span><h4>Live-adjusted modeled index</h4></div><small>Need / AI exposure</small></div>{subSectors.map(item=><div className="subsector-row" key={item.name}><b>{item.name}</b><div><span>Need <strong>{item.need}</strong></span><i><em style={{width:`${item.need}%`}}/></i><span>Exposure <strong>{item.exposure}</strong></span><i className="exposure"><em style={{width:`${item.exposure}%`}}/></i></div></div>)}<p>Modeled values are adjusted using the current public threat-feed pressure signal; they are directional estimates, not reported loss data.</p></div>}</article><article className="trend-panel"><header><div><span>Public signal</span><h3>Six-month KEV additions</h3></div></header><div className="trend-chart">{data?.threat.trend.map(point=><div key={point.month}><i style={{height:`${Math.max(5,point.count/maxTrend*100)}%`}}/><b>{point.count}</b><span>{point.month}</span></div>)}</div></article></div>
    <div className="sector-grid">{sectors.map(sector=><article key={sector.id} className="sector-card"><header><div><span>Risk index</span><b>{sector.risk}</b></div><div className="risk-gauge"><i style={{"--score":`${sector.risk*3.6}deg`} as React.CSSProperties}/></div></header><h3>{sector.name}</h3><div className="branch-list">{sector.branches.map(x=><span key={x}>{x}</span>)}</div><div className="score-pair"><div><span>Aronxx Tech need</span><b>{sector.need}/100</b></div><div><span>AI exposure</span><b>{sector.aiExposure}/100</b></div></div><div className="loss-range"><CircleDollarSign/><div><span>Modeled annual exposure</span><b>{money(sector.lossMin)}–{money(sector.lossMax)}</b></div></div><h4>Potential loss without controls</h4><ul>{sector.lossDrivers.map(x=><li key={x}>{x}</li>)}</ul><p><strong>Sensitive data:</strong> {sector.sensitiveData.join(" · ")}</p></article>)}</div>
    <div className="intel-method"><ShieldAlert/><div><b>How to read this dashboard</b><p>{data?.methodology}</p><div>{data?.sources.map(source=><a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.name} <span>↗</span><small>{source.cadence}</small></a>)}</div></div></div>
  </section>
}
