export type Section = { eyebrow?: string; title: string; text: string; items?: string[]; status?: "Available now" | "In development" | "Coming soon" | "Future vision" };
export type Page = { eyebrow: string; title: string; intro: string; sections: Section[] };
export const pages: Record<string, Page> = {
  home: { eyebrow: "AI data security, without the slowdown", title: "Use AI. Keep your data safe.", intro: "Aronxx Tech sits between your team and the AI tools they use—helping detect sensitive information before it leaves the company.", sections: [
    { eyebrow: "The problem", title: "Your firewall may protect your network. But what happens inside an AI chat box?", text: "Employees use AI for coding, research, writing and analysis. A useful prompt can accidentally contain source code, credentials, customer records or internal documents." },
    { eyebrow: "Detection in the moment", title: "Sensitive data gets caught before ‘Send,’ not after.", text: "Aronxx Tech can assess a prompt against policy, explain the risk and help the employee take the right action.", items: ["Detect", "Explain", "Warn", "Redact", "Continue"] },
    { eyebrow: "For security teams", title: "Visibility and control over AI usage.", text: "Review relevant events, warnings, blocked attempts, risk categories, AI platforms and policy outcomes in one place.", status: "In development" },
  ]},
  product: { eyebrow: "Meet Aronxx Tech", title: "Your AI data-security layer.", intro: "A practical control point between employees and generative AI—designed to protect sensitive information while keeping productive work moving.", sections: [
    { title: "Detection", text: "Identify potentially sensitive information in AI interactions, including credentials, source code, customer data and internal documents.", status: "In development" },
    { title: "Redaction", text: "Replace a risky fragment with a safe placeholder while keeping the rest of the prompt useful.", items: ["Before: API_KEY = sk_live_••••", "After: API_KEY = [REDACTED]"] , status: "In development"},
    { title: "Warnings and blocking", text: "Give employees context for medium-risk prompts and prevent high-risk submissions when organizational policy requires it.", status: "Future vision" },
    { title: "Security events", text: "Give administrators a clear record of relevant decisions without turning every interaction into noise.", status: "Future vision" },
  ]},
  "how-it-works": { eyebrow: "Adaptive control architecture", title: "Context enters. Governed outcomes emerge.", intro: "Aronxx Tech is designed as a coordinated set of policy, context and assurance planes. The public model shows operational boundaries without disclosing proprietary detection or decision logic.", sections: [
    { title: "Context envelope", text: "Interaction metadata is normalized into an organization-aware context envelope before policy evaluation begins." }, { title: "Signal lattice", text: "Multiple classification signals are correlated through a layered confidence model. Detection composition remains proprietary.", status: "In development" }, { title: "Policy fabric", text: "Organization-specific constraints are evaluated across identity, data class, destination and situational context.", status: "Future vision" }, { title: "Decision plane", text: "A governed response is selected through an abstracted orchestration layer rather than a single public rule path.", status: "Future vision" }, { title: "Assurance channel", text: "Relevant evidence can be transformed into controlled security events for authorized review.", status: "Future vision" }, { title: "Secure continuation", text: "Where policy permits, the workflow proceeds through a protected continuation boundary.", status: "Future vision" },
  ]},
  features: { eyebrow: "Product capabilities", title: "Everything needed for safer AI use.", intro: "The capability map below reflects Aronxx Tech’s early-stage roadmap. Status labels distinguish planned functionality from what exists today.", sections: [
    { title: "Sensitive data detection", text: "Identify potentially sensitive information in AI interactions.", status: "In development" }, { title: "Real-time warnings", text: "Notify employees when potentially risky information is detected.", status: "Future vision" }, { title: "Automatic redaction", text: "Help remove or mask sensitive fragments before submission.", status: "Future vision" }, { title: "Intelligent blocking", text: "Prevent high-risk information from being submitted under organizational policy.", status: "Future vision" }, { title: "Security events", text: "Provide visibility into relevant AI-security events.", status: "Future vision" }, { title: "AI usage visibility", text: "Help organizations understand AI usage patterns.", status: "Future vision" }, { title: "Custom policies", text: "Allow organizations to define security rules for their own data and teams.", status: "Future vision" }, { title: "AI risk score", text: "Provide a summarized view of AI-related security risk.", status: "Future vision" },
  ]},
  solutions: { eyebrow: "Who it’s for", title: "Security that meets teams where they are.", intro: "Aronxx Tech is being shaped for organizations adopting generative AI and looking for more control over sensitive data.", sections: [
    { title: "Startups", text: "Use AI while protecting proprietary information and early intellectual property." }, { title: "Technology companies", text: "Help protect source code, credentials and product knowledge." }, { title: "SaaS companies", text: "Add safeguards around customer and internal information." }, { title: "Professional services", text: "Help teams handle confidential client information more carefully." }, { title: "Growing businesses", text: "Introduce AI-security controls as adoption increases." },
  ]},
  dashboard: { eyebrow: "Industry risk intelligence", title: "See where secure AI controls matter most.", intro: "Compare industry and sub-industry exposure using a transparent model informed by live public vulnerability signals. Reported facts and modeled loss ranges are clearly separated.", sections: [
    { title: "Live public pressure", text: "CISA Known Exploited Vulnerabilities data is refreshed hourly when the source is available." }, { title: "12 industries · 48 sub-sectors", text: "Healthcare, technology, manufacturing, finance, pharmaceuticals, education, government, retail, telecom, logistics, legal and energy." }, { title: "Transparent estimates", text: "Financial ranges are modeled annual exposure for a mid-sized organization—not claims of recorded company loss." },
  ]},
  pilot: { eyebrow: "Aronxx Tech pilot", title: "Help us build the future of AI security.", intro: "We are speaking with early organizations to understand their AI-security challenges and shape the first version of Aronxx Tech.", sections: [{ title: "What the pilot explores", text: "Common AI tools, sensitive-data risks, policy needs and the employee experience." }, { title: "Who should apply", text: "Security, IT and technology leaders at organizations actively evaluating generative AI use." }]},
  about: { eyebrow: "About Aronxx Technologies", title: "Building security for the AI era.", intro: "Aronxx Technologies Pvt. Ltd. is focused on practical security solutions for the rapidly evolving AI ecosystem.", sections: [{ title: "Our focus", text: "Helping organizations adopt and use AI while maintaining better control over sensitive and confidential information." }, { title: "Our first product", text: "Aronxx Tech is our first product—a data-security layer for employee interactions with generative AI." }, { title: "Our philosophy", text: "Don’t block AI. Secure it." }]},
  contact: { eyebrow: "Contact", title: "Let’s talk about AI security.", intro: "Tell us what your team is trying to protect and how generative AI is being used across your organization.", sections: [{ title: "Start a conversation", text: "Use the form below to request a demo or discuss your AI-security priorities." }]},
  careers: { eyebrow: "Careers", title: "Help build Aronxx Tech.", intro: "We are interested in people who want to build thoughtful products at the intersection of AI and security.", sections: [{ title: "Areas of interest", text: "AI security, cybersecurity, browser technology, data protection, AI/LLM security and SaaS." }, { title: "Join the team", text: "Share your background and the problems you want to solve. Open roles will be published when available." }]},
  privacy: { eyebrow: "Legal", title: "Privacy policy", intro: "This notice explains how information submitted through the Aronxx Tech website is handled.", sections: [{ title: "Information collected", text: "Demo and pilot forms may collect your name, organization, work email, role and the information you choose to provide." }, { title: "How it is used", text: "Submitted information is used to respond to requests, evaluate pilot interest, improve the product and protect the website from misuse." }, { title: "Storage and access", text: "Form records are stored in the configured database and restricted to authorized administrators. Notification emails are sent through the configured email provider." }, { title: "Your choices", text: "You may request correction or deletion of submitted information by contacting Aronxx Technologies through the website contact channel." }]},
  terms: { eyebrow: "Legal", title: "Terms of use", intro: "By using this website, you agree to use its information and interactive features lawfully.", sections: [{ title: "Product status", text: "Aronxx Tech is an early-stage product. Concepts, demonstrations and roadmap labels do not guarantee current or future availability." }, { title: "Industry intelligence", text: "Public-feed data may change. Risk scores and financial ranges are decision-support estimates, not audit findings, legal advice or guaranteed outcomes." }, { title: "Acceptable use", text: "You may not interfere with the website, attempt unauthorized access, submit unlawful content or misuse its forms and data." }, { title: "No unsupported assurance", text: "No certification, compliance, integration, partnership or customer claim is made unless explicitly verified." }]},
} satisfies Record<string, Page>;
export type PageKey = keyof typeof pages;
