export type Section = { eyebrow?: string; title: string; text: string; items?: string[]; status?: "Available now" | "In development" | "Coming soon" | "Future vision" };
export type Page = { eyebrow: string; title: string; intro: string; sections: Section[] };
export const pages = {
  home: { eyebrow: "AI data security, without the slowdown", title: "Use AI. Keep your data safe.", intro: "Krypton sits between your team and the AI tools they use—helping detect sensitive information before it leaves the company.", sections: [
    { eyebrow: "The problem", title: "Your firewall may protect your network. But what happens inside an AI chat box?", text: "Employees use AI for coding, research, writing and analysis. A useful prompt can accidentally contain source code, credentials, customer records or internal documents." },
    { eyebrow: "Detection in the moment", title: "Sensitive data gets caught before ‘Send,’ not after.", text: "Krypton can assess a prompt against policy, explain the risk and help the employee take the right action.", items: ["Detect", "Explain", "Warn", "Redact", "Continue"] },
    { eyebrow: "For security teams", title: "Visibility and control over AI usage.", text: "Review relevant events, warnings, blocked attempts, risk categories, AI platforms and policy outcomes in one place.", status: "In development" },
  ]},
  product: { eyebrow: "Meet Krypton", title: "Your AI data-security layer.", intro: "A practical control point between employees and generative AI—designed to protect sensitive information while keeping productive work moving.", sections: [
    { title: "Detection", text: "Identify potentially sensitive information in AI interactions, including credentials, source code, customer data and internal documents.", status: "In development" },
    { title: "Redaction", text: "Replace a risky fragment with a safe placeholder while keeping the rest of the prompt useful.", items: ["Before: API_KEY = sk_live_••••", "After: API_KEY = [REDACTED]"] , status: "In development"},
    { title: "Warnings and blocking", text: "Give employees context for medium-risk prompts and prevent high-risk submissions when organizational policy requires it.", status: "Future vision" },
    { title: "Security events", text: "Give administrators a clear record of relevant decisions without turning every interaction into noise.", status: "Future vision" },
  ]},
  "how-it-works": { eyebrow: "A layer, not a lockdown", title: "Protection in five clear steps.", intro: "Krypton is designed to work quietly in the flow of AI use, with policy-based actions and visibility for security teams.", sections: [
    { title: "01 — Employee uses AI", text: "An employee prepares a prompt for an AI platform." }, { title: "02 — Krypton checks the content", text: "The content is checked for potentially sensitive information.", status: "In development" }, { title: "03 — Policy decision", text: "Based on organizational policy, the prompt may be allowed, warned, redacted or blocked.", status: "Future vision" }, { title: "04 — Employee continues", text: "Where appropriate, the employee can continue without exposing the original sensitive information.", status: "Future vision" }, { title: "05 — Security visibility", text: "Relevant events can be made visible to the organization’s security team.", status: "Future vision" },
  ]},
  features: { eyebrow: "Product capabilities", title: "Everything needed for safer AI use.", intro: "The capability map below reflects Krypton’s early-stage roadmap. Status labels distinguish planned functionality from what exists today.", sections: [
    { title: "Sensitive data detection", text: "Identify potentially sensitive information in AI interactions.", status: "In development" }, { title: "Real-time warnings", text: "Notify employees when potentially risky information is detected.", status: "Future vision" }, { title: "Automatic redaction", text: "Help remove or mask sensitive fragments before submission.", status: "Future vision" }, { title: "Intelligent blocking", text: "Prevent high-risk information from being submitted under organizational policy.", status: "Future vision" }, { title: "Security events", text: "Provide visibility into relevant AI-security events.", status: "Future vision" }, { title: "AI usage visibility", text: "Help organizations understand AI usage patterns.", status: "Future vision" }, { title: "Custom policies", text: "Allow organizations to define security rules for their own data and teams.", status: "Future vision" }, { title: "AI risk score", text: "Provide a summarized view of AI-related security risk.", status: "Future vision" },
  ]},
  solutions: { eyebrow: "Who it’s for", title: "Security that meets teams where they are.", intro: "Krypton is being shaped for organizations adopting generative AI and looking for more control over sensitive data.", sections: [
    { title: "Startups", text: "Use AI while protecting proprietary information and early intellectual property." }, { title: "Technology companies", text: "Help protect source code, credentials and product knowledge." }, { title: "SaaS companies", text: "Add safeguards around customer and internal information." }, { title: "Professional services", text: "Help teams handle confidential client information more carefully." }, { title: "Growing businesses", text: "Introduce AI-security controls as adoption increases." },
  ]},
  dashboard: { eyebrow: "Security dashboard preview", title: "Every relevant event, accounted for.", intro: "A concept preview of how security teams could understand AI usage, policy outcomes and concentrated risk. All figures shown are sample data.", sections: [
    { title: "492 safe prompts", text: "Sample demonstration data only." }, { title: "83 warnings", text: "Sample demonstration data only." }, { title: "27 blocked attempts", text: "Sample demonstration data only." }, { title: "112 security events", text: "Sample demonstration data only." }, { title: "10:43 AM — Source code detected", text: "Action: warning concept shown to the employee.", status: "Future vision" }, { title: "10:44 AM — Sensitive data redacted", text: "The safe prompt is shown as submitted in this product concept.", status: "Future vision" },
  ]},
  pilot: { eyebrow: "Krypton pilot", title: "Help us build the future of AI security.", intro: "We are speaking with early organizations to understand their AI-security challenges and shape the first version of Krypton.", sections: [{ title: "What the pilot explores", text: "Common AI tools, sensitive-data risks, policy needs and the employee experience." }, { title: "Who should apply", text: "Security, IT and technology leaders at organizations actively evaluating generative AI use." }]},
  about: { eyebrow: "About Aronxx Technologies", title: "Building security for the AI era.", intro: "Aronxx Technologies Pvt. Ltd. is focused on practical security solutions for the rapidly evolving AI ecosystem.", sections: [{ title: "Our focus", text: "Helping organizations adopt and use AI while maintaining better control over sensitive and confidential information." }, { title: "Our first product", text: "Krypton is our first product—a data-security layer for employee interactions with generative AI." }, { title: "Our philosophy", text: "Don’t block AI. Secure it." }]},
  contact: { eyebrow: "Contact", title: "Let’s talk about AI security.", intro: "Tell us what your team is trying to protect and how generative AI is being used across your organization.", sections: [{ title: "Start a conversation", text: "Use the form below to request a demo or discuss your AI-security priorities." }]},
  careers: { eyebrow: "Careers", title: "Help build Krypton.", intro: "We are interested in people who want to build thoughtful products at the intersection of AI and security.", sections: [{ title: "Areas of interest", text: "AI security, cybersecurity, browser technology, data protection, AI/LLM security and SaaS." }, { title: "Join the team", text: "Share your background and the problems you want to solve. Open roles will be published when available." }]},
  privacy: { eyebrow: "Legal", title: "Privacy policy", intro: "This website is an early-stage product website. A final privacy policy must be reviewed and approved before public launch.", sections: [{ title: "Contact information", text: "Information submitted through forms should only be used to respond to the request and evaluate pilot interest." }, { title: "Launch requirement", text: "Connect forms to an approved data processor and replace this notice with a legally reviewed policy before collecting personal data." }]},
  terms: { eyebrow: "Legal", title: "Terms of use", intro: "These terms are a launch placeholder and require legal review before the website is made public.", sections: [{ title: "Product status", text: "Krypton is an early-stage product. Website concepts and roadmap items do not constitute a guarantee of availability." }, { title: "No unsupported assurance", text: "No certification, compliance, integration, partnership or customer claim is made unless explicitly verified." }]},
} satisfies Record<string, Page>;
export type PageKey = keyof typeof pages;
